version: '3'

services:

  redis:
    image: redis:latest
    ports:
      - '6379:6379'

  db:
    image: postgres:13
    env_file:
      - .env
    volumes:
      - pg_data_habbits_tracker:/var/lib/postgresql/data/pgdata_habbits_tracker
    ports:
      - '5432:5432'

  app:
    build: .
    tty: true
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - '8001:8000'
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db
  celery:
    build: .
    env_file:
      - .env
    tty: true
    command: celery -A habbits_tracker worker -l INFO
    depends_on:
      - redis
      - app

  celery_beat:
    build: .
    tty: true
    env_file:
      - .env
    command: celery -A habbits_tracker beat -l INFO -S django
    depends_on:
      - redis
      - app

volumes:
  pg_data_habbits_tracker: