# Generated by Django 5.0.1 on 2024-02-03 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=255, verbose_name='место выполнения')),
                ('time', models.TimeField(verbose_name='время, когда выполняется привычка')),
                ('action', models.CharField(max_length=255, verbose_name='действие')),
                ('is_pleasure', models.BooleanField(default=False, verbose_name='признак приятной привычки')),
                ('periodicity', models.PositiveIntegerField(choices=[(1, 'Каждые понедельник, среда, пятница'), (2, 'Каждые вторник, четверг, суббота'), (3, 'Каждый будний день'), (4, 'Каждые выходные')], default=1, verbose_name='периодичность')),
                ('reward', models.CharField(blank=True, max_length=255, null=True, verbose_name='вознаграждение')),
                ('duration', models.DurationField(verbose_name='длительность выполнения')),
                ('is_public', models.BooleanField(default=False, verbose_name='признак публичности')),
                ('related_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_habit', to='main.habit', verbose_name='связанная привычка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
                'ordering': ('pk',),
            },
        ),
    ]
